directive @requireAuth on FIELD_DEFINITION

type BusinessContactInfo {
  name: String
  whatsapp: BigInt
  phone: BigInt
  zello: String
  defaultLocation: String    
}

"Business Contact info"
type Query{
   BusinessContactInfo(
      "Business id"
      _id: ID
   ): BusinessContactInfo @requireAuth
}